name: Feature Template
description: 새로운 기능을 추가할 때 사용하는 템플릿
title: "[FEAT] "
labels: [enhancement]
body: 
  - type: markdown 
    attributes: 
      value: | 
        당신의 기여에 항상 감사드립니다! 

  - type: checkboxes 
    attributes: 
      label: Search before adding issue
      description: |
        Please search the [issues](https://github.com/Rimember/ringchat/issues) to see if a similar feature request already exists.
      options:
        - label: I have searched the ringchat [issues](https://github.com/Rimember/ringchat/issues) and found no similar feature request.
          required: true 

  - type: textarea 
    attributes: 
      label: Description
      description: A short description of your feature. 
      placeholder: | 
        새로 추가할 기능이 무엇인지 간단하게 설명해주세요. 

  - type: textarea
    attributes:
      label: Todo
      description: List the tasks to be completed. Use `- [ ]` to create checkboxes.
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3