{
 "title": "Backend Observability",
 "tags": [
  "Prometheus",
  "Loki"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "LogTime", "label": "Log Time", "query": "label_values(time)" },
   { "name": "FilePath", "label": "File Path", "query": "label_values(file_path)" },
   { "name": "LogLevel", "label": "Log Level", "query": "label_values(level)" }
  ]
 },
 "panels": [
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Status code",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 1, "w": 6, "h": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_response_status_total{job=\"backend\", path!~\"/(metrics/backend|metrics/postgres)\"}",
     "legendFormat": "{{status_code}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 1, "w": 9, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"backend\", handler!=\"/metrics\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Total Request Count",
   "type": "bargauge",
   "gridPos": { "x": 15, "y": 1, "w": 9, "h": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_count_total{job=\"backend\", path!~\"/(metrics/backend|metrics/postgres)\"}",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "x": 0, "y": 9, "w": 24, "h": 1 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 10, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "x": 10, "y": 10, "w": 9, "h": 8 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "All logs", "type": "row", "gridPos": { "x": 0, "y": 18, "w": 24, "h": 1 } },
  {
   "title": "FastAPI Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 19, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "{job=\"backend_logs\"} |= ``"
    }
   ]
  }
 ]
}