{
 "title": "Frontend Observability",
 "tags": [
  "Prometheus",
  "Loki"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "LogTime", "label": "Log Time", "query": "label_values(time)" },
   { "name": "FilePath", "label": "File Path", "query": "label_values(file_path)" },
   { "name": "LogLevel", "label": "Log Level", "query": "label_values(level)" }
  ]
 },
 "panels": [
  { "title": "CPU status", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "1 minute load average ",
   "type": "timeseries",
   "description": "CPU가 처리해야 할 작업의 양을 나타내는 숫자 \nnode_load1 = 1  => 하나의 코어가 지속적으로 작업을 처리하고 있는 상태 \nnode_load1 > 1  => 작업 요청을 처리하기 위해 대기 중인 작업이 있는 상태 \nnode_load1 < 1  => 작업 요청을 처리하기에 여유가 있는 상태  ",
   "gridPos": { "x": 0, "y": 1, "w": 8, "h": 8 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{__name__}}" },
    {},
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "table",
   "gridPos": { "x": 8, "y": 1, "w": 16, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"(idle|nice|steal|irq)\"}[5m])) by (mode, cpu)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory & Disk status", "type": "row", "gridPos": { "x": 0, "y": 9, "w": 24, "h": 1 } },
  {
   "title": "Memory usage",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 10, "w": 10, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O (Read)",
   "type": "gauge",
   "gridPos": { "x": 10, "y": 10, "w": 5, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_read_bytes_total{job=\"node_exporter\",device=~\"vda|vdb\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O (Write)",
   "type": "gauge",
   "gridPos": { "x": 15, "y": 10, "w": 5, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_written_bytes_total{job=\"node_exporter\",device=~\"vda|vdb\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Network Status", "type": "row", "gridPos": { "x": 0, "y": 19, "w": 24, "h": 1 } },
  {
   "title": "Network usage",
   "type": "stat",
   "gridPos": { "x": 0, "y": 20, "w": 9, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{job=\"node_exporter\", device=\"eth0\"}",
     "legendFormat": "Transmit"
    },
    {
     "expr": "node_network_receive_bytes_total{job=\"node_exporter\", device=\"eth0\"}",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Network error",
   "type": "stat",
   "gridPos": { "x": 9, "y": 20, "w": 8, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_errs_total{job=\"node_exporter\", device=\"eth0\"}",
     "legendFormat": "Transmit"
    },
    {
     "expr": "node_network_receive_errs_total{job=\"node_exporter\", device=\"eth0\"}",
     "legendFormat": "Receive"
    }
   ]
  },
  { "title": "Page Performance", "type": "row", "gridPos": { "x": 0, "y": 26, "w": 24, "h": 1 } },
  {
   "title": "Web vitals",
   "type": "table",
   "gridPos": { "x": 0, "y": 27, "w": 24, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (path, __name__) (web_vitals_ttfb{job=\"frontend\"})",
     "legendFormat": "{{path}} - TTFB"
    },
    {
     "expr": "sum by (path, __name__) (web_vitals_fcp{job=\"frontend\"})",
     "legendFormat": "{{path}} - FCP"
    },
    {
     "expr": "sum by (path, __name__) (web_vitals_lcp{job=\"frontend\"})",
     "legendFormat": "{{path}} - LCP"
    },
    {
     "expr": "sum by (path, __name__) (web_vitals_cls{job=\"frontend\"})",
     "legendFormat": "{{path}} - CLS"
    },
    {
     "expr": "sum by (path, __name__) (web_vitals_inp{job=\"frontend\"})",
     "legendFormat": "{{path}} - INP"
    }
   ]
  },
  {
   "title": "Page Load (TTFB, FCP, LCP) - p75",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 33, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (__name__) (web_vitals_ttfb{job=\"frontend\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (__name__) (web_vitals_fcp{job=\"frontend\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (__name__) (web_vitals_lcp{job=\"frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift(CLS) - p75",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 33, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (__name__) (web_vitals_cls{job=\"frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interaction to Next Paint",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 33, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (__name__) (web_vitals_inp{job=\"frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ALL Logs", "type": "row", "gridPos": { "x": 0, "y": 41, "w": 24, "h": 1 } },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "x": 0, "y": 42, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "{job=\"frontend_logs\"} |= ``"
    }
   ]
  }
 ]
}