{
 "title": "Postgres Observability",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Database Stats", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "Concurrent user",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 1, "h": 6, "w": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_active_connections{job=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total cache hit ratio",
   "type": "gauge",
   "gridPos": { "x": 5, "y": 1, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_total_cache_hit_ratio{job=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit ratio per table",
   "type": "stat",
   "gridPos": { "x": 11, "y": 1, "w": 7, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(cache_hit_ratio_user_info{job=\"postgres\"}, \"last_part\", \"$1\", \"__name__\", \"cache_hit_ratio_(.*)\")",
     "legendFormat": "{{last_part}}"
    },
    {
     "expr": "label_replace(cache_hit_ratio_folder{job=\"postgres\"}, \"last_part\", \"$1\", \"__name__\", \"cache_hit_ratio_(.*)\")",
     "legendFormat": "{{last_part}}"
    },
    {
     "expr": "label_replace(cache_hit_ratio_link{job=\"postgres\"}, \"last_part\", \"$1\", \"__name__\", \"cache_hit_ratio_(.*)\")",
     "legendFormat": "{{last_part}}"
    },
    {
     "expr": "label_replace(cache_hit_ratio_link_stat{job=\"postgres\"}, \"last_part\", \"$1\", \"__name__\", \"cache_hit_ratio_(.*)\")",
     "legendFormat": "{{last_part}}"
    },
    {
     "expr": "label_replace(cache_hit_ratio_link_summary_embedding{job=\"postgres\"}, \"last_part\", \"$1\", \"__name__\", \"cache_hit_ratio_(.*)\")",
     "legendFormat": "{{last_part}}"
    },
    {
     "expr": "label_replace(cache_hit_ratio_chat_room{job=\"postgres\"}, \"last_part\", \"$1\", \"__name__\", \"cache_hit_ratio_(.*)\")",
     "legendFormat": "{{last_part}}"
    },
    {
     "expr": "label_replace(cache_hit_ratio_chat_room_link{job=\"postgres\"}, \"last_part\", \"$1\", \"__name__\", \"cache_hit_ratio_(.*)\")",
     "legendFormat": "{{last_part}}"
    },
    {
     "expr": "label_replace(cache_hit_ratio_message{job=\"postgres\"}, \"last_part\", \"$1\", \"__name__\", \"cache_hit_ratio_(.*)\")",
     "legendFormat": "{{last_part}}"
    },
    {
     "expr": "label_replace(cache_hit_ratio_rating{job=\"postgres\"}, \"last_part\", \"$1\", \"__name__\", \"cache_hit_ratio_(.*)\")",
     "legendFormat": "{{last_part}}"
    }
   ]
  },
  {
   "title": "Deadlock count",
   "type": "gauge",
   "gridPos": { "x": 18, "y": 1, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_deadlock_count{job=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insert/Update/Delete",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 7, "w": 11, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(pg_insert_rate{job=\"postgres\"}, \"DML\", \"$1\", \"__name__\", \"pg_(.*)_rate\")",
     "legendFormat": "{{DML}}"
    },
    {
     "expr": "label_replace(pg_update_rate{job=\"postgres\"}, \"DML\", \"$1\", \"__name__\", \"pg_(.*)_rate\")",
     "legendFormat": "{{DML}}"
    },
    {
     "expr": "label_replace(pg_delete_rate{job=\"postgres\"}, \"DML\", \"$1\", \"__name__\", \"pg_(.*)_rate\")",
     "legendFormat": "{{DML}}"
    }
   ]
  }
 ]
}