name: Backend Release Green Deployment

on:
  push:
    branches:
      - release-test
    paths:
      - 'backend/**'

env:
  DOCKER_IMAGE_NAME: rimember/ringchat-backend:green-latest
  DOCKER_CONTAINER_NAME: backend-green

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY}} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY}} \
            -t ${{ env.DOCKER_IMAGE_NAME }} ./backend

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}

      - name: Deploy Green container on remote server
        uses: appleboy/ssh-action@v1.1.0
        with:
          key: ${{ secrets.BACK_SERVER_SSH_KEY }}
          host: ${{ secrets.BACK_SERVER_HOST }}
          username: ubuntu
          script: |
            docker stop ${{ env.DOCKER_CONTAINER_NAME }} || true
            docker rm ${{ env.DOCKER_CONTAINER_NAME }} || true
            docker pull ${{ env.DOCKER_IMAGE_NAME }}
            docker run -d --name ${{ env.DOCKER_CONTAINER_NAME }} -p 8000:8000 ${{ env.DOCKER_IMAGE_NAME }}
