name: CD Pipeline

on:
  push:
    branches:
      - ci-cd-test

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > server-key.pem
          chmod 600 server-key.pem

      - name: Deploy to Server
        run: |
          ssh -i server-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP}} "
          cd ringchat &&
          docker-compose pull &&
          docker-compose up -d &&
          docker-compose exec backend alembic upgrade head
          "