name: Frontend Release Green Deployment

on:
  push:
    branches:
      - release-test
    paths:
      - 'frontend/**'

env:
  DOCKER_IMAGE_NAME: rimember/ringchat-frontend:green-latest
  DOCKER_CONTAINER_NAME: frontend-green

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }} ./frontend

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}

      - name: Deploy Green container on remote server
        uses: appleboy/ssh-action@v1.1.0
        with:
          key: ${{ secrets.FRONT_SERVER_SSH_KEY }}
          host: ${{ secrets.FRONT_SERVER_HOST }}
          username: ubuntu
          script: |
            docker stop ${{ env.DOCKER_CONTAINER_NAME }} || true
            docker rm ${{ env.DOCKER_CONTAINER_NAME }} || true
            docker pull ${{ env.DOCKER_IMAGE_NAME }}
            docker run -d --name ${{ env.DOCKER_CONTAINER_NAME }} -p 3000:3000 \
              -e ${{ secrets.NEXT_PUBLIC_API_URL }} $DOCKER_IMAGE_NAME
