name: Frontend Release Green Deployment

on:
  push:
    branches:
      - release-test
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: "rimember/ringchat-frontend:green-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME ./frontend

      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_IMAGE_NAME

      - name: Deploy Green container on remote server
        uses: appleboy/ssh-action@v1.1.0
        with:
          key: ${{ secrets.FRONT_SERVER_SSH_KEY }}
          host: ${{ secrets.FRONT_SERVER_HOST }}
          username: ubuntu
          script: |
            docker stop frontend-green || true
            docker rm frontend-green || true
            docker pull $DOCKER_IMAGE_NAME
            docker run -d --name frontend-green -p 3000:3000 \
              -e ${{ secrets.NEXT_PUBLIC_API_URL }} $DOCKER_IMAGE_NAME
