name: Test Envs
on:
  push:
    branches:
      - release-test

jobs:
  test-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create SSH key file
        run: |
          echo "${{ secrets.FRONT_SERVER_SSH_KEY }}" > ~/fkey.pem
          chmod 400 ~/fkey.pem
      
      - name: Check container port
        run: |
          BLUE_PORT=$(ssh -i ~/fkey.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.FRONT_SERVER_HOST }} \
          "docker inspect --format='{{.HostConfig.PortBindings}}' frontend-prod1 | awk '{print \$2}' | awk -F '}' '{print \$1}'")
          echo "$BLUE_PORT"
          echo "BLUE_PORT=$BLUE_PORT" >> $GITHUB_ENV
      
      - name: Check env
        run: |
          echo "port: ${{ env.BLUE_PORT }}"