name: Test Envs
on:
  push:
    branches:
      - release-test

jobs:
  test-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check container port
        run: |
          BLUE_PORT=$(ssh -o StrictHostKeyChecking=no -i ${{ secrets.FRONT_SERVER_SSH_KEY }} ubuntu@${{ secrets.FRONT_SERVER_HOST }} \
          "docker inspect --format='{{.HostConfig.PortBindings}}' frontend-prod1 | awk '{print \$2}' | awk -F '}' '{print \$1}'")
          echo "BLUE_PORT=$BLUE_PORT"
          echo "BLUE_PORT=$BLUE_PORT" >> $GITHUB_ENV

      - name: Use BLUE_PORT variable
        run: |
          echo "The blue container is running on port: ${{ env.BLUE_PORT }}"